import json
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import umap

def load_and_flatten_data(input_file):
    """Loads the nested JSON and flattens it into a single list of papers."""
    with open(input_file, "r", encoding="utf-8") as f:
        dataset = json.load(f)
        
    papers = []
    for funder, works in dataset.items():
        for work in works:
            # Combine abstract and concepts into one rich text string for vectorization
            concept_words = " ".join([c["concept"] for c in work.get("concepts", [])])
            rich_text = f"{work.get('title', '')} {concept_words} {work.get('abstract', '')}"
            
            work["rich_text"] = rich_text
            papers.append(work)
            
    return papers

def normalize_coordinates(coords, scale=100):
    """Centers the 3D coordinates around 0,0,0 and scales them for Three.js."""
    coords -= coords.mean(axis=0)
    max_val = np.max(np.abs(coords))
    return (coords / max_val) * scale

def process_pipeline():
    input_file = "./data/funding_concept_landscape.json"
    output_file = "./data/dashboard_ready.json"
    
    print("1. Loading dataset...")
    papers = load_and_flatten_data(input_file)
    print(f"   -> Loaded {len(papers)} papers total.")
    
    if not papers:
        print("No papers found. Exiting.")
        return

    texts = [p["rich_text"] for p in papers]
    
    print("2. Vectorizing text (TF-IDF)...")
    vectorizer = TfidfVectorizer(stop_words='english', max_features=5000)
    text_vectors = vectorizer.fit_transform(texts)
    
    print("3. Running UMAP to generate 3D coordinates...")
    umap_model = umap.UMAP(n_neighbors=15, min_dist=0.1, n_components=3, random_state=42)
    raw_3d_coords = umap_model.fit_transform(text_vectors)
    
    print("4. Normalizing coordinates for Three.js...")
    scaled_coords = normalize_coordinates(raw_3d_coords, scale=100)
    
    print("5. Formatting and saving output...")
    dashboard_data = []
    for i, paper in enumerate(papers):
        dashboard_data.append({
            "title": paper.get("title"),
            "funder": paper.get("funder"),
            "citations": paper.get("citations") or 0,
            "topic": paper.get("primary_topic"),
            "concepts": [c["concept"] for c in paper.get("concepts", [])[:3]],
            "year": paper.get("year") or "N/A",
            "doi": paper.get("doi") or "",
            # Safely maps the explicit key generated by your harvest pipeline
            "author_citation": paper.get("author_citation") or "Unknown",
            "x": round(float(scaled_coords[i][0]), 3),
            "y": round(float(scaled_coords[i][1]), 3),
            "z": round(float(scaled_coords[i][2]), 3)
        })
        
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump(dashboard_data, f, ensure_ascii=False)
        
    print(f"\nSUCCESS! Output saved to '{output_file}'. Move this to your dashboard/public/ folder.")

if __name__ == "__main__":
    process_pipeline()